package com.example.skillswap.admin.enums;

public enum AdminActionType {
    USER_SUSPENDED,
    USER_BANNED,
    USER_DELETED,
    USER_PASSWORD_RESET,
    SKILL_MERGED,
    SKILL_DELETED,
    POST_DELETED,
    POST_MARKED_SPAM,
    REVIEW_DELETED,
    REPORT_IGNORED,
    REPORT_WARNED,
    REPORT_CONTENT_DELETED,
    REPORT_USER_BANNED,
    NOTIFICATION_SENT,
    IMAGE_DELETED,
    SETTINGS_UPDATED
}